### ISSUE TITLE
Set up vulcanize for Web Components

### ISSUE THREAD

**Issue by Nevraeka** [thewebplatform/thewebplatform.today#10]

**Comment by pertrai1** [comment]
Who is this assigned to and what is the criteria for the setup? @Nevraeka

**Comment by Nevraeka** [comment]
I will assign this to myself. I applied for with GoDaddy for free Open Source SSL for one year (because our project is open source) Hopefully that will work - otherwise we pay for the cert & divshot requires a few things and GoDaddy (our domain registar) requires updating domain information.

http://docs.divshot.com/guides/ssl

**Comment by Nevraeka** [comment]
See this for a detailed explanation- https://www.polymer-project.org/articles/concatenating-web-components.html

**Comment by prateekjadhwani** [comment]
With Polymer starter kit, we wont have to setup vulcanize at all. It will come prepackaged in it.

**Comment by Nevraeka** [comment]
good. Something we can close then
