### ISSUE TITLE
Cucumber Integration?

### ISSUE THREAD

**Issue by pertrai1** [thewebplatform/thewebplatform.today#16]
@DannyBlueDesign Do you think we would need something like Cucumber for testing or can we wait on this? Don't know if you use it or not, and did not know if you thought it would be beneficial for this app at the start

**Comment by Nevraeka** [comment]
Not the biggest fan of Cucumber but if you guys think we can use it I am open. Keep in mind this will add a ruby dependency we get rid of with the switch to libsass. Web Component tester uses saucelabs or web driver I believe

**Comment by pertrai1** [comment]
We will stay away for now because of the setup time that we don't need to production
