### ISSUE TITLE
Add contribution/getstarted guide

### ISSUE THREAD

**Issue by prateekjadhwani** [thewebplatform/thewebplatform.today#20]
The project needs a startup guide for contributors so that they can set up the workspace locally and start testing/working on the modules on their local machines.

**Comment by Nevraeka** [comment]
Agreed.Not sure how to prioritize this one but I agree that it is not clear at all. The README updates might be a higher priority I would think just because that is where you typically find information on building, deploying and dev setup in general.

**Comment by prateekjadhwani** [comment]
Once Polymer 1.0 port is complete, we should be able to re-use a bunch of stuff from the `polymer starter kit`.

**Comment by Nevraeka** [comment]
sounds good

**Comment by prateekjadhwani** [comment]
I think this is done. Can someone else confirm it as well.
