### ISSUE TITLE
Update Polymer to 1.0

### ISSUE THREAD

**Issue by prateekjadhwani** [thewebplatform/thewebplatform.today#21]
It seems that the project is still using Polymer 0.5 as a dependency. We will need to update it to Polymer 1.0 as soon as possible.

**Comment by Nevraeka** [comment]
:+1: Agreed

**Comment by prateekjadhwani** [comment]
I am trying to replace the project files with [Polymer starter kit](https://github.com/polymerelements/polymer-starter-kit/releases) and I see a lot of files that i have no clue about. @Nevraeka can you confirm if these files are being used anywhere, or if they can be removed.

| File name | Folder |
| --- | --- |
| basic.html | [/app](https://github.com/thewebplatform/thewebplatform.today/tree/master/app) |
| error.html | [/app](https://github.com/thewebplatform/thewebplatform.today/tree/master/app) |
| humans.txt | [/app](https://github.com/thewebplatform/thewebplatform.today/tree/master/app) |
| icons/* | [/app/images/icons](https://github.com/thewebplatform/thewebplatform.today/tree/master/app/images/icons) |
| index.html | [/app](https://github.com/thewebplatform/thewebplatform.today/tree/master/app) |
| manifest.webapp | [/app](https://github.com/thewebplatform/thewebplatform.today/tree/master/app) |
| styleguide.html | [/app](https://github.com/thewebplatform/thewebplatform.today/tree/master/app) |
| styles/* | [/app/styles/](https://github.com/thewebplatform/thewebplatform.today/tree/master/app/styles) |
| README.md | [/app](https://github.com/thewebplatform/thewebplatform.today/tree/master/app) |
| divshot.json | [/](https://github.com/thewebplatform/thewebplatform.today) |

**This is what I am thinking about these files**
- Using `iron-icons` for all the icons might be a better choice rather than maintaining icons again at our end.
- The css will be inside the element, and it will be reusable, since we will be reusing the element using the css. So do we still need the scss files?
- I have no clue about other files.

**Comment by Nevraeka** [comment]
divshot.json & README are used but not by the front end. Everything else is fair game

**Comment by Nevraeka** [comment]
:+1:
