### ISSUE TITLE
Feature Request : Update comments system to Disqus

### ISSUE THREAD

**Issue by prateekjadhwani** [thewebplatform/thewebplatform.today#22]
Would it be okay to update the existing comment system to Disqus. We should be able to create a discus element and simply provide the parameters they require as  attributes to the element. This element can then be used inside the web-app.

**Comment by Nevraeka** [comment]
:+1: sounds good

**Comment by prateekjadhwani** [comment]
Okay, so we should be able to re-use this element [disqus-comments](https://github.com/divshot/disqus-comments). 
- [x] But it still needs work for Polymer 1.0 port.
- [ ] Better documentation on how to use.

**Comment by prateekjadhwani** [comment]
I am not sure if **divshot** team is accepting the [PR for Polymer 1.0](https://github.com/divshot/disqus-comments/pull/1) or not. Its been more than a week. :(

**Comment by prateekjadhwani** [comment]
The PR was merged few days ago. Moving to done state.
