### ISSUE TITLE
Task : Application Theme

### ISSUE THREAD

**Issue by prateekjadhwani** [thewebplatform/thewebplatform.today#24]
We will need the application theme for **The Web Platform Today** site based on http://www.materialpalette.com/ . This theme will be consistent through out the app.

**Comment by Nevraeka** [comment]
http://www.materialpalette.com/blue/deep-orange

thoughts?

**Comment by prateekjadhwani** [comment]
looks good to me. I will grab the apptheme file and update it in the project. 

I will close the issue after that. Thanks

**Comment by Nevraeka** [comment]
:+1:
