### ISSUE TITLE
Implement Routing for the web app

### ISSUE THREAD

**Issue by prateekjadhwani** [thewebplatform/thewebplatform.today#30]
The basics for the routing is already available in the Polymer starter kit. The only thing that needs to be done is identify routes and add their configuration in the file [routing.html](https://github.com/thewebplatform/thewebplatform.today/blob/master/app/elements/routing.html).

**Comment by Nevraeka** [comment]
Also may need to update Divshot's routing (which might mean removing routes - idk)

**Comment by prateekjadhwani** [comment]
I will use divshot as a server while working on the route, so that I can remove the redundant routes between the two.

**Comment by Nevraeka** [comment]
:+1:

**Comment by prateekjadhwani** [comment]
Done in https://github.com/thewebplatform/thewebplatform.today/pull/34
