### ISSUE TITLE
Search next page routing

### ISSUE THREAD

**Issue by Link2Twenty** [thewebplatform/thewebplatform.today#33]
If you search and have the order set to something other than default you can't go to the next page.

https://customelements.io/search/polymer?s=pushed_at:desc
press next page and you get
https://customelements.io/search/polymer?page=2
what you want is
https://customelements.io/search/polymer?s=pushed_at:desc&page=2
this does work when typed in.

**Comment by Link2Twenty** [comment]
Incorrect git somehow... My apologies

**Comment by prateekjadhwani** [comment]
Lol no worries, 

Now i am curious about customelements.io site as well :P
