### ISSUE TITLE
Lo-Res Wireframes

### ISSUE THREAD

**Issue by Nevraeka** [thewebplatform/thewebplatform.today#5]
Finalize UX/UI with @DannyBlueDesign . Need to set up a google hangout to discuss mockups, accessibility, and flow. All members are welcome to attend.

**Comment by pertrai1** [comment]
Let me know when this hangout will occur so I can be part of it

**Comment by Nevraeka** [comment]
:+1: @pertrai1

**Comment by pertrai1** [comment]
@Nevraeka @DannyBlueDesign - here is a quick first crack at a lo-res wireframe to get ideas floating around about the components and modules we will need to hook up

**Comment by Nevraeka** [comment]
What is the best way to view this? I have Balsamiq installed

**Comment by pertrai1** [comment]
You can either go to the branch and to the assets dir, where you can click on the .png, or fetch the branch if you don't have it already.

**Comment by Nevraeka** [comment]
this is a great start! I think we should focus on mobile UI/UX to get the most important pieces flushed out. I'll commit a few ideas ASAP. Great work @pertrai1 :+1:

**Comment by pertrai1** [comment]
Yeah there are some other device factors that need to be flushed out.  We can talk about the idea of mobile and other devices @eisaksen
