### ISSUE TITLE
Doc for app requirements

### ISSUE THREAD

**Issue by pertrai1** [thewebplatform/thewebplatform.today#8]
It would be good to have document(s) that describe the requirements for the app, so we can then split apart tasks. If need be, we can use something like Pivotal Tracker for the stories and tasks?

**Comment by Nevraeka** [comment]
Good idea. I'll create a google doc or sheet on trello for this and we can turn them into issues based on that. What do you think @pertrai1 & @DannyBlueDesign

**Comment by pertrai1** [comment]
Yeah let's go with the Google doc for now @Nevraeka @DannyBlueDesign
